<?php

session_start();
include 'common/connect.php';

//session code

if(!isset($_SESSION['user_id']))
{
    header('location:home.php');
}
//finish

$user_id = $_SESSION['user_id'];

//api keys  
$apiKey = "rzp_test_pXtLNzDfIlN645";
$profile_data = $obj->query("select * from user where user_id='$user_id'");
$profile = $profile_data->fetch_object();

$res = $obj->query("SELECT * FROM `money_donation` WHERE user_id='$user_id' ORDER by date DESC limit 1;");
$r = $res->fetch_object();


// if (isset($_POST['submit'])) {
//   # code...
//   $amt = $_POST['amt'];
//   $desc = $_POST['desc'];
//   $date = date('Y-m-d');
//   $user_id = $_SESSION['user_id'];

//   $exe = $obj->query("insert into money_donation(user_id,amount,description,date) values('$user_id','$amt','$desc','$date')");



//   if($exe ){
//         echo "<script>alert('money donation Successfullly');</script>";
//     }
//     else {
//         echo "<script>alert(' error');</script>";
//     }
// }




?>
<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!doctype html>
<html lang="zxx">


  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Helping-Hand(NGO)
    </title>
    <!-- Template CSS -->
    <link rel="stylesheet" href="assets/css/style-starter.css">
    <!-- Template CSS -->
    <link href="//fonts.googleapis.com/css?family=Poppins:300,400,400i,500,600,700&display=swap" rel="stylesheet">
    <!-- Template CSS -->
  </head>

<body>

  <!--w3l-header-->

  <?php include 'common/header.php'; ?>
<!--/header-->
<div class="inner-banner">
</div>
  <!-- /donation-form -->
  <section class="w3l-contact-11">
    <div class="form-41-mian py-5">
      <div class="container py-lg-4">
        <div class="row align-form-map">
        <div class="col-lg-6 contact-left pr-lg-4">
          
     
        </div>
        
        <div class="col-lg-12 form-inner-cont">
          <div class="title-content text-left">
            <!-- <h3 class="hny-title mb-lg-5 mb-4">Please money Donate</h3> -->
          </div>
              <form action="http://localhost/Helping_Hand/user1/success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo intval($r->amount) * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo $r->m_d;?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Helping Hand"
    data-description="NGO - Help Needy Persons"
    data-image="https://oibp1.000webhostapp.com/logo.PNG"
    data-prefill.name="<?php echo $profile->name;?>"
    data-prefill.email="<?php echo $profile->email;?>"
    data-prefill.contact="<?php echo $profile->contact;?>"
    data-theme.color="#ff9902"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
        </div>
        </div>
      </div>
      </div>
     
    </section>
  <!-- //contact-form -->
  <!-- footer-66 -->

  <?php include 'common/footer.php'; ?>
  <!--//footer-66 -->
</body>

</html>

<script src="assets/js/jquery-3.3.1.min.js"></script>
<!-- disable body scroll which navbar is in active -->

<!-- disable body scroll which navbar is in active -->
<script>
  $(function () {
    $('.navbar-toggler').click(function () {
      $('body').toggleClass('noscroll');
    })
  });
</script>
<!-- disable body scroll which navbar is in active -->

<!--/MENU-JS-->
<script>
  $(window).on("scroll", function () {
    var scroll = $(window).scrollTop();

    if (scroll >= 80) {
      $("#site-header").addClass("nav-fixed");
    } else {
      $("#site-header").removeClass("nav-fixed");
    }
  });

  //Main navigation Active Class Add Remove
  $(".navbar-toggler").on("click", function () {
    $("header").toggleClass("active");
  });
  $(document).on("ready", function () {
    if ($(window).width() > 991) {
      $("header").removeClass("active");
    }
    $(window).on("resize", function () {
      if ($(window).width() > 991) {
        $("header").removeClass("active");
      }
    });
  });
</script>
<!--//MENU-JS-->
<script src="assets/js/bootstrap.min.js"></script>